#!/usr/bin/env python3
"""Convert the MAME 'asteroid' ROM set into a C header for AEROLITE.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Asteroids has no graphics ROMs: the picture is a display list walked by the
Digital Vector Generator. There are three program ROMs and one vector ROM.
"""
import sys, zlib
from pathlib import Path

# (filename, CPU address, size)
PROGRAM = [('035145-04e.ef2', 0x6800, 0x800),
           ('035144-04e.h2',  0x7000, 0x800),
           ('035143-02.j2',   0x7800, 0x800)]
VECTOR  =  ('035127-02.np3',  0x5000, 0x800)

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'asteroid')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    prog = b''.join(load(romdir, n, s) for n, _, s in PROGRAM)   # contiguous 0x6800-0x7FFF
    vec = load(romdir, VECTOR[0], VECTOR[2])
    out = ['/* asteroids_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef ASTEROIDS_ROMS_H', '#define ASTEROIDS_ROMS_H', '#include <stdint.h>', '',
           '/* program ROM, CPU 0x6800-0x7FFF */',
           c_array('ast_rom', prog, '[0x1800]'), '',
           '/* vector ROM, CPU 0x5000-0x57FF */',
           c_array('ast_vecrom', vec, '[0x800]'), '',
           '#endif']
    (outdir / 'asteroids_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "asteroids_roms.h"}')

if __name__ == '__main__':
    main()
