#!/usr/bin/env python3
"""Convert the MAME 'centiped' ROM set into a C header for CHILOPODA.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

The graphics ROM pair is decoded with MAME's layouts (two planes, the high plane in the
second ROM) into one pixel per byte:
  ce_tiles[256*64]     8x8 tiles, values 0-3
  ce_sprites[128*128]  8x16 sprites, values 0-3
The program ROMs are concatenated as the CPU sees them at 0x2000-0x3FFF.
"""
import sys, zlib
from pathlib import Path

EXPECTED = {  # name: (size, crc32)
    '136001-407.d1':  (0x800, 0xc4d995eb), '136001-408.e1':  (0x800, 0xbcdebe1b),
    '136001-409.fh1': (0x800, 0x66d7b04a), '136001-410.j1':  (0x800, 0x33ce4640),
    '136001-211.f7':  (0x800, 0x880acfb9), '136001-212.hj7': (0x800, 0xb1397029),
    '136001-213.p4':  (0x100, 0x6fa3093a),
}

def load(romdir, name):
    data = (romdir / name).read_bytes()
    size, crc = EXPECTED[name]
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    if zlib.crc32(data) & 0xffffffff != crc:
        print(f'  warning: {name} crc32 {zlib.crc32(data):08x} != expected {crc:08x}')
    print(f'  {name}: {len(data)} bytes ok')
    return data

def decode(gfx, width, height, count):
    """Two bitplanes: plane 1 (high bit) in the second half of the region, plane 0 in the first.
    Each plane holds `height` bytes per character, one byte per row, MSB = leftmost pixel."""
    half = len(gfx) // 2
    out = bytearray(count * width * height)
    for c in range(count):
        for y in range(height):
            lo = gfx[c * height + y]
            hi = gfx[half + c * height + y]
            for x in range(width):
                bit = 7 - x
                out[(c * height + y) * width + x] = (((hi >> bit) & 1) << 1) | ((lo >> bit) & 1)
    return bytes(out)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'centiped')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    rom = b''.join(load(romdir, n) for n in ('136001-407.d1', '136001-408.e1', '136001-409.fh1', '136001-410.j1'))
    gfx = load(romdir, '136001-211.f7') + load(romdir, '136001-212.hj7')
    load(romdir, '136001-213.p4')     # sync PROM: not needed by the emulation, checked for completeness
    tiles = decode(gfx, 8, 8, 256)
    sprites = decode(gfx, 8, 16, 128)
    out = ['/* centiped_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef CENTIPED_ROMS_H', '#define CENTIPED_ROMS_H', '#include <stdint.h>', '',
           c_array('ce_rom', rom, '[0x2000]'), '',
           c_array('ce_tiles', tiles, '[256 * 64]'), '',
           c_array('ce_sprites', sprites, '[128 * 128]'), '',
           '#endif']
    (outdir / 'centiped_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "centiped_roms.h"}')

if __name__ == '__main__':
    main()
