#!/usr/bin/env python3
"""Convert the MAME 'timeplt' ROM set into a C header for CHRONO.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('tm1', 0x2000), ('tm2', 0x2000), ('tm3', 0x2000)]
SND  =  ('tm7', 0x1000)
CHR  =  ('tm6', 0x2000)
SPR  = [('tm4', 0x2000), ('tm5', 0x2000)]
PROM = [('timeplt.b4', 0x20), ('timeplt.b5', 0x20), ('timeplt.e9', 0x100), ('timeplt.e12', 0x100)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'timeplt')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    out = ['/* timeplt_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef TIMEPLT_ROMS_H', '#define TIMEPLT_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU */', c_array('tp_rom', cat(PROG), '[0x6000]'), '',
           '/* sound CPU */', c_array('tp_snd', load(romdir, SND[0], SND[1]), '[0x1000]'), '',
           '/* characters */', c_array('tp_chr', load(romdir, CHR[0], CHR[1]), '[0x2000]'), '',
           '/* sprites */', c_array('tp_spr', cat(SPR), '[0x4000]'), '',
           '/* PROMs */', c_array('tp_prom', cat(PROM), '[0x240]'), '',
           '#endif']
    (outdir / 'timeplt_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "timeplt_roms.h"}')

if __name__ == '__main__':
    main()
