#!/usr/bin/env python3
"""Convert the MAME 'arkanoidu' ROM set into a C header for VAUS.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Note on the MCU: this set carries a reconstructed 68705 program rather than one of
the dumps MAME lists. It is valid 6805 code and the emulator runs it, but its CRC is
checked loosely for that reason.
"""
import sys, zlib
from pathlib import Path

MAIN = [('a75-19.ic17', 0x8000), ('a75-18.ic16', 0x8000)]
MCU  =  ('arknoidu.ic14', 0x800)
GFX  = [('a75-03.ic64', 0x8000), ('a75-04.ic63', 0x8000), ('a75-05.ic62', 0x8000)]
PROM = [('a75-07.ic24', 0x200), ('a75-08.ic23', 0x200), ('a75-09.ic22', 0x200)]  # red, green, blue

def load(romdir, name, size, strict=True):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def cat(romdir, items):
    return b''.join(load(romdir, n, s) for n, s in items)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'arkanoid')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    proms = [load(romdir, n, s) for n, s in PROM]
    out = ['/* arkanoid_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef ARKANOID_ROMS_H', '#define ARKANOID_ROMS_H', '#include <stdint.h>', '',
           '/* Z80 program, 0x0000-0xFFFF (only the low 48K is populated) */',
           c_array('ak_rom', cat(romdir, MAIN), '[0x10000]'), '',
           '/* the 68705 sound... input MCU */',
           c_array('ak_mcu', load(romdir, *MCU, strict=False), '[0x800]'), '',
           '/* three bit planes, one 32 KB ROM each */',
           c_array('ak_gfx', cat(romdir, GFX), '[0x18000]'), '',
           c_array('ak_prom_r', proms[0], '[0x200]'), '',
           c_array('ak_prom_g', proms[1], '[0x200]'), '',
           c_array('ak_prom_b', proms[2], '[0x200]'), '',
           '#endif']
    (outdir / 'arkanoid_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "arkanoid_roms.h"}')

if __name__ == '__main__':
    main()
