#!/usr/bin/env python3
"""Convert the MAME 'rbtapper' ROM set into a C header for KEG.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('rbtpg0.bin', 0x4000), ('rbtpg1.bin', 0x4000), ('rbtpg2.bin', 0x4000), ('rbtpg3.bin', 0x2000)]
SND  = [('5788', 0x1000), ('5787', 0x1000), ('5786', 0x1000), ('5785', 0x1000)]
GFX1 = [('rbtbg1.bin', 0x4000), ('rbtbg0.bin', 0x4000)]
GFX2 = [('rbtfg1.bin', 0x4000), ('rbtfg0.bin', 0x4000), ('rbtfg3.bin', 0x4000), ('rbtfg2.bin', 0x4000),
        ('rbtfg5.bin', 0x4000), ('rbtfg4.bin', 0x4000), ('rbtfg7.bin', 0x4000), ('rbtfg6.bin', 0x4000)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'rbtapper')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    out = ['/* rbtapper_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef RBTAPPER_ROMS_H', '#define RBTAPPER_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU */', c_array('tap_rom', cat(PROG), '[0xE000]'), '',
           '/* SSIO CPU */', c_array('tap_snd', cat(SND), '[0x4000]'), '',
           '/* tiles */', c_array('tap_gfx1', cat(GFX1), '[0x8000]'), '',
           '/* sprites */', c_array('tap_gfx2', cat(GFX2), '[0x20000]'), '',
           '#endif']
    (outdir / 'rbtapper_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "rbtapper_roms.h"}')

if __name__ == '__main__':
    main()
