#!/usr/bin/env python3
"""Convert the MAME 'btime' ROM set into a C header for GRIDDLE.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('aa04.9b', 0x1000), ('aa06.13b', 0x1000), ('aa05.10b', 0x1000), ('aa07.15b', 0x1000)]   # 0xC000 up
SND  =  ('ab14.12h', 0x1000)
GFX1 = [('aa12.7k', 0x1000), ('ab13.9k', 0x1000), ('ab10.10k', 0x1000), ('ab11.12k', 0x1000), ('aa8.13k', 0x1000), ('ab9.15k', 0x1000)]
GFX2 = [('ab00.1b', 0x800), ('ab01.3b', 0x800), ('ab02.4b', 0x800)]
BGMAP = ('ab03.6b', 0x800)

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'btime')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    prog = bytes(0x1000) + cat(PROG)        # the program begins at 0xC000; 0xB000-0xBFFF is empty
    out = ['/* btime_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef BTIME_ROMS_H', '#define BTIME_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU, 0xB000-0xFFFF */', c_array('bt_rom', prog, '[0x5000]'), '',
           '/* sound CPU */', c_array('bt_snd', load(romdir, SND[0], SND[1]), '[0x1000]'), '',
           '/* characters and sprites */', c_array('bt_gfx1', cat(GFX1), '[0x6000]'), '',
           '/* background tiles */', c_array('bt_gfx2', cat(GFX2), '[0x1800]'), '',
           '/* background map */', c_array('bt_bgmap', load(romdir, BGMAP[0], BGMAP[1]), '[0x800]'), '',
           '#endif']
    (outdir / 'btime_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "btime_roms.h"}')

if __name__ == '__main__':
    main()
