#!/usr/bin/env python3
"""Convert the MAME 'mpatrolw' ROM set into a C header for BUGGY.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('mpa-1w.3m', 0x1000), ('mpa-2w.3l', 0x1000), ('mpa-3w.3k', 0x1000), ('mpa-4w.3j', 0x1000)]
SND  = [('mp-s1.1a', 0x1000)]
TX   = [('mpe-4w.3f', 0x1000), ('mpe-5w.3e', 0x1000)]        # plane 0, plane 1
SP   = [('mpb-2.3m', 0x1000), ('mpb-1.3n', 0x1000)]          # plane 1, plane 0 (plane 2 is absent)
BG   = [('mpe-1.3l', 0x1000), ('mpe-2.3k', 0x1000), ('mpe-3.3h', 0x1000)]   # mountains, hills, city
PROMS = [('mpc-4a.2a', 0x200), ('mpc-3.1m', 0x20), ('mpc-1.1f', 0x20), ('mpc-2.2h', 0x100)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'mpatrolw')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    out = ['/* mpatrolw_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef MPATROLW_ROMS_H', '#define MPATROLW_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU */', c_array('mp_rom', cat(PROG), '[0x4000]'), '',
           '/* sound CPU, 0x7000-0x7FFF */', c_array('mp_snd', cat(SND), '[0x1000]'), '',
           '/* characters: two 4 KB planes */', c_array('mp_tx', cat(TX), '[0x2000]'), '',
           '/* sprites: two 4 KB planes (bit 1 first) */', c_array('mp_sp', cat(SP), '[0x2000]'), '',
           '/* backgrounds: mountains, hills, city */', c_array('mp_bg', cat(BG), '[0x3000]'), '',
           '/* PROMs: character palette 512, background palette 32, sprite palette 32, sprite lookup 256 */',
           c_array('mp_proms', cat(PROMS), '[0x340]'), '',
           '#endif']
    (outdir / 'mpatrolw_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "mpatrolw_roms.h"}')

if __name__ == '__main__':
    main()
