#!/usr/bin/env python3
"""Convert the MAME 'mrdo' ROM set into a C header for BIGTOP.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('a4-01.bin', 0x2000), ('c4-02.bin', 0x2000), ('e4-03.bin', 0x2000), ('f4-04.bin', 0x2000)]
FG   = [('s8-09.bin', 0x1000), ('u8-10.bin', 0x1000)]
BG   = [('r8-08.bin', 0x1000), ('n8-07.bin', 0x1000)]
SPR  = [('h5-05.bin', 0x1000), ('k5-06.bin', 0x1000)]
PROM = [('u02--2.bin', 0x20), ('t02--3.bin', 0x20), ('f10--1.bin', 0x20), ('j10--4.bin', 0x20)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'mrdo')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    out = ['/* mrdo_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef MRDO_ROMS_H', '#define MRDO_ROMS_H', '#include <stdint.h>', '',
           '/* Z80 program */', c_array('md_rom', cat(PROG), '[0x8000]'), '',
           '/* foreground characters */', c_array('md_fg', cat(FG), '[0x2000]'), '',
           '/* background characters */', c_array('md_bg', cat(BG), '[0x2000]'), '',
           '/* sprites */', c_array('md_spr', cat(SPR), '[0x2000]'), '',
           '/* PROMs */', c_array('md_prom', cat(PROM), '[0x80]'), '',
           '#endif']
    (outdir / 'mrdo_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "mrdo_roms.h"}')

if __name__ == '__main__':
    main()
