#!/usr/bin/env python3
"""Convert the MAME 'galaxian' ROM set into a C header for ARMADA.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

MAIN = [('galmidw.u', 0x800), ('galmidw.v', 0x800), ('galmidw.w', 0x800), ('galmidw.y', 0x800), ('7l', 0x800)]
GFX  = [('1h.bin', 0x800), ('1k.bin', 0x800)]
PROM =  ('6l.bpr', 0x20)

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'galaxian')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    rom = b''.join(load(romdir, n, s) for n, s in MAIN)
    gfx = b''.join(load(romdir, n, s) for n, s in GFX)
    prom = load(romdir, PROM[0], PROM[1])
    out = ['/* galaxian_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef GALAXIAN_ROMS_H', '#define GALAXIAN_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU, 0x0000-0x27FF */', c_array('gx_rom', rom, '[0x2800]'), '',
           '/* character and sprite planes */', c_array('gx_gfx', gfx, '[0x1000]'), '',
           '/* colour PROM */', c_array('gx_prom', prom, '[0x20]'), '',
           '#endif']
    (outdir / 'galaxian_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "galaxian_roms.h"}')

if __name__ == '__main__':
    main()
