#!/usr/bin/env python3
"""Convert the MAME 'mario' ROM set into a C header for PLUMBER.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('tma1-c-7f_f.7f', 0x2000), ('tma1-c-7e_f.7e', 0x2000), ('tma1-c-7d_f.7d', 0x2000), ('tma1-c-7c_f.7c', 0x1000)]
SND  =  ('tma1-c-6k_e.6k', 0x1000)
CHR  = [('tma1-v-3f.3f', 0x1000), ('tma1-v-3j.3j', 0x1000)]
SPR  = [('tma1-v-7m.7m', 0x1000), ('tma1-v-7n.7n', 0x1000), ('tma1-v-7p.7p', 0x1000),
        ('tma1-v-7s.7s', 0x1000), ('tma1-v-7t.7t', 0x1000), ('tma1-v-7u.7u', 0x1000)]
PROM =  ('tma1-c-4p_1.4p', 0x200)

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'mario')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    prog = b''.join(load(romdir, n, s) for n, s in PROG)       # 0x0000-0x5FFF, then the 0xF000 block
    snd = bytearray(load(romdir, SND[0], SND[1]))
    # The M58715 boots from a small internal ROM (undumped) that ends by jumping to the
    # external ROM at 0x101 - the STRT T that runs the sound board's clock. A ROMless part
    # enters at 0x100 and never starts the timer, so the tune player hangs in its idle loop.
    # MAME documents the one-byte fix: make the reset vector CALL $101 instead of $100.
    if snd[0] == 0x34 and snd[1] == 0x00:
        snd[1] = 0x01
        print('  (reset vector patched to CALL $101, as for a ROMless 8039)')
    snd = bytes(snd)
    chr_ = b''.join(load(romdir, n, s) for n, s in CHR)
    spr = b''.join(load(romdir, n, s) for n, s in SPR)
    prom = load(romdir, PROM[0], PROM[1])
    out = ['/* mario_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef MARIO_ROMS_H', '#define MARIO_ROMS_H', '#include <stdint.h>', '',
           '/* Z80 program: 0x0000-0x5FFF, then the 4 KB at 0xF000 */', c_array('mb_rom', prog, '[0x7000]'), '',
           '/* 8039 program */', c_array('mb_snd', snd, '[0x1000]'), '',
           '/* characters, 3f then 3j */', c_array('mb_chr', chr_, '[0x2000]'), '',
           '/* sprites, three planes */', c_array('mb_spr', spr, '[0x6000]'), '',
           '/* colour PROM */', c_array('mb_prom', prom, '[0x200]'), '',
           '#endif']
    (outdir / 'mario_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "mario_roms.h"}')

if __name__ == '__main__':
    main()
