#!/usr/bin/env bash
#
# Flash a complete medal: bootloader, partition table, ota_data, launcher,
# marquee artwork, and every game that has been built - each to its own slot.
#
# Offsets come from build/manifest.json and partitions.csv, both generated by
# tools/configure.py, so they cannot drift from what the firmware expects.
#
#   tools/flash_all.sh [port]
#   tools/flash_all.sh --dry-run
#
# Run from the host. Docker Desktop on macOS cannot reach USB devices.
set -euo pipefail
cd "$(dirname "$0")/.."

DRY=0; PORT=""
for a in "$@"; do
    case "$a" in
        --dry-run) DRY=1 ;;
        *) PORT="$a" ;;
    esac
done

BUILD=build_docker
MANIFEST=build/manifest.json
PROJECTS="${PROJECTS_DIR:-$HOME/Projects}"

[ -f "$MANIFEST" ]        || { echo "no $MANIFEST - run ./minimame build" >&2; exit 1; }
[ -f "$BUILD/minimame.bin" ] || { echo "no launcher build - run ./minimame build" >&2; exit 1; }
[ -f lcd/marquees.bin ]   || { echo "no lcd/marquees.bin - run ./minimame build" >&2; exit 1; }

mqart_off=$(awk -F',' '/^mqart/ {gsub(/ /,"",$4); print $4}' partitions.csv)

ARGS=(0x0     "$BUILD/bootloader/bootloader.bin"
      0x8000  "$BUILD/partition_table/partition-table.bin"
      0xf000  "$BUILD/ota_data_initial.bin"
      0x20000 "$BUILD/minimame.bin"
      "$mqart_off" lcd/marquees.bin)

echo
printf '  %-22s %-10s %s\n' COMPONENT OFFSET FILE
printf '  %-22s %-10s %s\n' launcher 0x20000 "$BUILD/minimame.bin"
printf '  %-22s %-10s %s\n' artwork "$mqart_off" lcd/marquees.bin

missing=0
while IFS=$'\t' read -r rom title project offset; do
    [ -n "$rom" ] || continue
    bin=""
    if [ -n "$project" ] && [ "$project" != "null" ]; then
        # a game repo builds to <PROJECT>/build_docker/<lowercase project>.bin
        cand="$PROJECTS/$project/build_docker/$(echo "$project" | tr 'A-Z' 'a-z').bin"
        [ -f "$cand" ] && bin="$cand"
    fi
    if [ -n "$bin" ]; then
        printf '  %-22s %-10s %s\n' "$title" "$offset" "${bin#$PROJECTS/}"
        ARGS+=("$offset" "$bin")
    else
        printf '  %-22s %-10s %s(not built - slot left empty)%s\n' "$title" "$offset" $'\033[2m' $'\033[0m'
        missing=$((missing+1))
    fi
done < <(python3 -c "
import json
for g in json.load(open('$MANIFEST'))['games']:
    print('\t'.join([g['rom'], g['title'], str(g.get('project') or ''), hex(g['offset'])]))
")

ESPTOOL=$(command -v esptool.py || echo "python3 -m esptool")
CMD=($ESPTOOL --chip esp32c6 ${PORT:+-p "$PORT"} -b 460800
     --before default_reset --after hard_reset
     write_flash --flash_mode dio --flash_size 16MB --flash_freq 80m "${ARGS[@]}")

echo
[ "$missing" -gt 0 ] && echo "  $missing slot(s) empty - those games show as NOT INSTALLED in the menu"

if [ "$DRY" = 1 ]; then
    echo; echo "  dry run, would execute:"; echo; printf '   %q' "${CMD[@]}"; echo; echo
    exit 0
fi
echo; echo "  flashing..."; echo
"${CMD[@]}"
