#!/usr/bin/env python3
"""Convert the MAME 'invaders' ROM set into a C header for PHALANX.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

# in address order: .h at 0x0000, .g at 0x0800, .f at 0x1000, .e at 0x1800
MAIN = [('invaders.h', 0x800), ('invaders.g', 0x800), ('invaders.f', 0x800), ('invaders.e', 0x800)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'invaders')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    rom = b''.join(load(romdir, n, s) for n, s in MAIN)
    out = ['/* invaders_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef INVADERS_ROMS_H', '#define INVADERS_ROMS_H', '#include <stdint.h>', '',
           '/* 8080 program, 0x0000-0x1FFF */', c_array('si_rom', rom, '[0x2000]'), '',
           '#endif']
    (outdir / 'invaders_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "invaders_roms.h"}')

if __name__ == '__main__':
    main()
