#!/usr/bin/env python3
"""Convert the MAME 'joust' ROM set into a C header for OSTRICH.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

PROG = [('3006-13.1b', 0x1000), ('3006-14.2b', 0x1000), ('3006-15.3b', 0x1000), ('3006-16.4b', 0x1000),
        ('3006-17.5b', 0x1000), ('3006-18.6b', 0x1000), ('3006-19.7b', 0x1000), ('3006-20.8b', 0x1000),
        ('3006-21.9b', 0x1000)]                                     # 0x0000-0x8FFF
PROG_HI = [('3006-22.10b', 0x1000), ('3006-23.11b', 0x1000), ('3006-24.12b', 0x1000)]   # 0xD000-0xFFFF
SND = [('joust.snd', 0x1000)]                                       # sound CPU 0xF000-0xFFFF

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'joust')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    cat = lambda lst: b''.join(load(romdir, n, s) for n, s in lst)
    out = ['/* joust_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef JOUST_ROMS_H', '#define JOUST_ROMS_H', '#include <stdint.h>', '',
           '/* main CPU, 0x0000-0x8FFF (banked over the video RAM) */', c_array('jo_rom_lo', cat(PROG), '[0x9000]'), '',
           '/* main CPU, 0xD000-0xFFFF */', c_array('jo_rom_hi', cat(PROG_HI), '[0x3000]'), '',
           '/* sound CPU, 0xF000-0xFFFF */', c_array('jo_snd', cat(SND), '[0x1000]'), '',
           '#endif']
    (outdir / 'joust_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "joust_roms.h"}')

if __name__ == '__main__':
    main()
