#!/usr/bin/env python3
"""Convert the MAME 'llander' ROM set into a C header for REGOLITH.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Four program ROMs and three vector ROMs; the PROM is the DVG's state machine and
is not needed. (The set also carries 034569-02.b1 at 0x7800.)
"""
import sys, zlib
from pathlib import Path

PROGRAM = [('034572-02.f1',  0x6000, 0x800), ('034571-02.de1', 0x6800, 0x800),
           ('034570-01.c1',  0x7000, 0x800), ('034569-02.b1',  0x7800, 0x800)]
VECTOR  = [('034599-01.r3',  0x4800, 0x800), ('034598-01.np3', 0x5000, 0x800),
           ('034597-01.m3',  0x5800, 0x800)]

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'llander')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    prog = b''.join(load(romdir, n, s) for n, _, s in PROGRAM)
    vec = b''.join(load(romdir, n, s) for n, _, s in VECTOR)
    out = ['/* llander_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef LLANDER_ROMS_H', '#define LLANDER_ROMS_H', '#include <stdint.h>', '',
           '/* program ROM, CPU 0x6000-0x7FFF */', c_array('ll_rom', prog, '[0x2000]'), '',
           '/* vector ROM, CPU 0x4800-0x5FFF */', c_array('ll_vecrom', vec, '[0x1800]'), '',
           '#endif']
    (outdir / 'llander_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "llander_roms.h"}')

if __name__ == '__main__':
    main()
